### ISSUE TITLE
pandas version 2

### ISSUE THREAD

**Issue by nberliner** [DarioHett/entsoe-client#18]
Hey, have you tried the client with pandas version 2.*? Currently it is still using 1.*. Do you see any issue in updating the dependency? Thanks!

**Comment by DarioHett** [comment]
Going forward the flattening of records should be separated from the dataframe library, such that alternatives (e.g. Polars, Ibis) can be used.

**Comment by nberliner** [comment]
Separating flattening of the records from the dataframe library would be a nice add-on. Since Pandas is so widely used I don't think it is an obstacle right now.

Please feel free to close this issue since you already updated the dependency (thanks!)
